/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author zcmgyu
 */
public final class DialogRoomDetail extends javax.swing.JDialog {

    /**
     * Creates new form DialogRoomDetail
     * @param parent
     * @param modal
     */
    public DialogRoomDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initInfo();
        initCompoundBorder();
        initRoomCharge();
    }
    CompoundBorder compoundBorder;
    void initCompoundBorder() {
        //        splitPane.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Border line = BorderFactory.createLineBorder(Color.lightGray, 2);
        Border empty = new EmptyBorder(5, 10, 5, 10);
        compoundBorder = new CompoundBorder(line, empty);
        listFamily.setBorder(compoundBorder);
        txtCleaning.setBorder(compoundBorder);
        txtElectric.setBorder(compoundBorder);
        txtParking.setBorder(compoundBorder);
        txtWater.setBorder(compoundBorder);
        txtRoomCharge.setBorder(compoundBorder);
        // Label Format
        lblFamMember.setBorder(compoundBorder);
        lblService.setBorder(compoundBorder);
    }
    
    void initRoomCharge() {
        String sql = "SELECT TOP 1 r.Room, s.[Service Name], e.[Date], e.Expense FROM tblService_Expense se, tblService s, tblExpense e, tblRoom r\n" +
                    "WHERE s.ID = se.ServiceID AND e.ID = se.ExpenseID AND r.ServiceID = s.ID AND r.ID = " + ShareData.getInstance().getRoomID() + "\n" +
                    "ORDER BY [Date] DESC";
        
        try (Connection cn = Tools.getConn();
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql)
                ){
            while (rs.next()) {                
                txtRoomCharge.setText("Ngày " + rs.getDate(3) + " trả " + rs.getString(4) + " VNĐ");
            }
            txtRoomCharge.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(DialogRoomDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    ///
    void initInfo() {
        System.out.println("IN RA ROOM: " + ShareData.getInstance().getRoomID());
        this.setTitle("Phòng " + ShareData.getInstance().getRoomName());
        String sql = "SELECT ID, Name FROM tblHuman WHERE RoomID = " + ShareData.getInstance().getRoomID();
        DefaultListModel<HumanModal> listFam = new DefaultListModel<>();
        ArrayList<Integer> listMemberID;
        try (Connection cn = Tools.getConn();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql)
            ){
            while (rs.next()) {
                HumanModal human = new HumanModal(rs.getInt(1), rs.getString(2));
                listFam.addElement(human);
            }
            listFamily.setModel(listFam);
        } catch (SQLException ex) {
            Logger.getLogger(DialogRoomDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        edit = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        add = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFamily = new javax.swing.JList();
        lblFamMember = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblService = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClose = new org.jdesktop.swingx.JXButton();
        btnReport = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jXButton4 = new org.jdesktop.swingx.JXButton();
        jXButton5 = new org.jdesktop.swingx.JXButton();
        lblCleaningFee = new javax.swing.JLabel();
        lblParkingFee = new javax.swing.JLabel();
        txtRoomCharge = new javax.swing.JFormattedTextField();
        txtElectric = new javax.swing.JFormattedTextField();
        txtWater = new javax.swing.JFormattedTextField();
        txtCleaning = new javax.swing.JFormattedTextField();
        txtParking = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jXButton6 = new org.jdesktop.swingx.JXButton();
        jXButton7 = new org.jdesktop.swingx.JXButton();
        jXButton8 = new org.jdesktop.swingx.JXButton();
        jXButton9 = new org.jdesktop.swingx.JXButton();
        jXButton10 = new org.jdesktop.swingx.JXButton();

        popupMenu.setBackground(new java.awt.Color(255, 255, 255));
        popupMenu.setBorderPainted(false);
        popupMenu.setLabel("");

        edit.setText("Chỉnh sửa");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        popupMenu.add(edit);

        delete.setText("Xóa thông báo");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        popupMenu.add(delete);

        add.setText("Đăng thông báo");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        popupMenu.add(add);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setBorder(null);

        listFamily.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listFamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listFamilyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listFamilyMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listFamily);

        lblFamMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFamMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFamMember.setText("<html>Thành viên<br/>trong hộ</html>");

        lblService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblService.setText("Dịch vụ");
        lblService.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setText("Tiền điện");

        jLabel4.setText("Tiền nước");

        jLabel5.setText("Tiền phòng");

        btnClose.setText("Thoát");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnReport.setText("Báo hỏng");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        jXButton3.setBackground(new java.awt.Color(255, 255, 255));
        jXButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jXButton3.setToolTipText("Delete");
        jXButton3.setOpaque(false);
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });

        jXButton4.setBackground(new java.awt.Color(255, 255, 255));
        jXButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        jXButton4.setToolTipText("Delete");
        jXButton4.setOpaque(false);

        jXButton5.setBackground(new java.awt.Color(255, 255, 255));
        jXButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus_1.png"))); // NOI18N
        jXButton5.setToolTipText("Delete");
        jXButton5.setOpaque(false);
        jXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton5ActionPerformed(evt);
            }
        });

        lblCleaningFee.setText("Phí vệ sinh");

        lblParkingFee.setText("Phí đậu xe");

        txtRoomCharge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤¤#,##0"))));
        txtRoomCharge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRoomCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomChargeActionPerformed(evt);
            }
        });

        txtElectric.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtElectric.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtWater.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0 VNĐ"))));
        txtWater.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtCleaning.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0 VNĐ"))));
        txtCleaning.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtParking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0 VNĐ"))));
        txtParking.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jXButton6.setBackground(new java.awt.Color(255, 255, 255));
        jXButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/launch.png"))); // NOI18N
        jXButton6.setToolTipText("Delete");
        jXButton6.setOpaque(false);

        jXButton7.setBackground(new java.awt.Color(255, 255, 255));
        jXButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/launch.png"))); // NOI18N
        jXButton7.setToolTipText("Delete");
        jXButton7.setOpaque(false);

        jXButton8.setBackground(new java.awt.Color(255, 255, 255));
        jXButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/launch.png"))); // NOI18N
        jXButton8.setToolTipText("Delete");
        jXButton8.setOpaque(false);

        jXButton9.setBackground(new java.awt.Color(255, 255, 255));
        jXButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/launch.png"))); // NOI18N
        jXButton9.setToolTipText("Delete");
        jXButton9.setOpaque(false);

        jXButton10.setBackground(new java.awt.Color(255, 255, 255));
        jXButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/launch.png"))); // NOI18N
        jXButton10.setToolTipText("Delete");
        jXButton10.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(lblCleaningFee)
                                    .addComponent(lblParkingFee))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCleaning, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWater)
                                    .addComponent(txtElectric)
                                    .addComponent(txtParking)
                                    .addComponent(txtRoomCharge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jXButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap()))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jXButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jXButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFamMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClose, btnReport});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFamMember, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblService)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRoomCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtElectric, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWater, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jXButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCleaningFee))
                    .addComponent(jXButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtParking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblParkingFee))
                    .addComponent(jXButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void check(MouseEvent evt) {
        if (evt.isPopupTrigger()) { //if the event shows the menu
            System.out.println("Gọi hàm Click chuột phải");
            popupMenu.show(listFamily, evt.getX(), evt.getY()); //and show the menu
        }
    }
    
    private void listFamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFamilyMousePressed
        check(evt);
    }//GEN-LAST:event_listFamilyMousePressed

    private void listFamilyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFamilyMouseReleased
        check(evt);
    }//GEN-LAST:event_listFamilyMouseReleased

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
//        selectedIndex = leftList.getSelectedIndex();
        EditHumanDialog ep = new EditHumanDialog(null, true);
        ep.setLocationRelativeTo(this);
        ep.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
//        List<AnnounceModal> list = leftList.getSelectedValuesList();
//        delete(list);
//        ShareData.getInstance().getPa().initTitle();
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //        btnSwitchToEditorActionPerformed(evt);
    }//GEN-LAST:event_addActionPerformed

    private void jXButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton5ActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton3ActionPerformed

    private void txtRoomChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomChargeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRoomDetail dialog = new DialogRoomDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add;
    private org.jdesktop.swingx.JXButton btnClose;
    private org.jdesktop.swingx.JXButton btnReport;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem edit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.jdesktop.swingx.JXButton jXButton10;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton4;
    private org.jdesktop.swingx.JXButton jXButton5;
    private org.jdesktop.swingx.JXButton jXButton6;
    private org.jdesktop.swingx.JXButton jXButton7;
    private org.jdesktop.swingx.JXButton jXButton8;
    private org.jdesktop.swingx.JXButton jXButton9;
    private javax.swing.JLabel lblCleaningFee;
    private javax.swing.JLabel lblFamMember;
    private javax.swing.JLabel lblParkingFee;
    private javax.swing.JLabel lblService;
    private javax.swing.JList listFamily;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JFormattedTextField txtCleaning;
    private javax.swing.JFormattedTextField txtElectric;
    private javax.swing.JFormattedTextField txtParking;
    private javax.swing.JFormattedTextField txtRoomCharge;
    private javax.swing.JFormattedTextField txtWater;
    // End of variables declaration//GEN-END:variables
}
