/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author PhiLong
 */
public final class DialogDetailHuman1 extends javax.swing.JDialog {

    int id;

    /**
     * Creates new form DetailHumanForm
     *
     * @param parent
     * @param modal
     */
    public DialogDetailHuman1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initHuman();
        initCompoundBorder();
//        setDisable();
    }

    Image img;
    CompoundBorder compoundBorder;

    public void initCompoundBorder() {
        txtBirthPlace.setBorder(ToolsDesign.comboundBorderAll());
        txtEmail.setBorder(ToolsDesign.comboundBorderAll());
        txtIDCard.setBorder(ToolsDesign.comboundBorderAll());
        txtNation.setBorder(ToolsDesign.comboundBorderAll());
        txtNativeCountry.setBorder(ToolsDesign.comboundBorderAll());
        txtOccupation.setBorder(ToolsDesign.comboundBorderAll());
        txtReligion.setBorder(ToolsDesign.comboundBorderAll());
        txtRoomID.setBorder(ToolsDesign.comboundBorderAll());
        txtUserName.setBorder(ToolsDesign.comboundBorderAll());
        txtWorkPlace.setBorder(ToolsDesign.comboundBorderAll());
    }

    void setDisable() {
        txtBirthDay.setEditable(false);
        txtArrivalDate.setEditable(false);
        txtBirthPlace.setEditable(false);
        txtEmail.setEditable(false);
        txtIDCard.setEditable(false);
        txtNation.setEditable(false);
        txtNativeCountry.setEditable(false);
        txtOccupation.setEditable(false);
        txtReligion.setEditable(false);
        txtRoomID.setEditable(false);
        txtUserName.setEditable(false);
        txtWorkPlace.setEditable(false);
        btnMale.setEnabled(false);
        btnFemale.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        btnPrevious = new org.jdesktop.swingx.JXButton();
        btnNext = new org.jdesktop.swingx.JXButton();
        btnExit = new org.jdesktop.swingx.JXButton();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        top = new javax.swing.JPanel();
        txtRoomID = new javax.swing.JTextField();
        txtReligion = new javax.swing.JTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtNation = new javax.swing.JTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtBirthDay = new org.jdesktop.swingx.JXDatePicker();
        txtNativeCountry = new javax.swing.JTextField();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        txtUserName = new javax.swing.JTextField();
        txtIDCard = new javax.swing.JTextField();
        txtBirthPlace = new javax.swing.JTextField();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtWorkPlace = new javax.swing.JTextField();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        txtOccupation = new javax.swing.JTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        lblImage = new org.jdesktop.swingx.JXLabel();
        txtArrivalDate = new org.jdesktop.swingx.JXDatePicker();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        txtEmail = new javax.swing.JTextField();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bottom.setBackground(new java.awt.Color(204, 204, 204));
        bottom.setPreferredSize(new java.awt.Dimension(548, 50));

        btnPrevious.setBackground(new java.awt.Color(255, 255, 255));
        btnPrevious.setBorder(null);
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chevron-left.png"))); // NOI18N
        btnPrevious.setOpaque(false);

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chevron-right.png"))); // NOI18N
        btnNext.setOpaque(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jXButton1.setBackground(new java.awt.Color(255, 255, 255));
        jXButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chevron-double-right.png"))); // NOI18N
        jXButton1.setOpaque(false);

        jXButton2.setBackground(new java.awt.Color(255, 255, 255));
        jXButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chevron-double-left.png"))); // NOI18N
        jXButton2.setOpaque(false);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bottomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNext, btnPrevious, jXButton1, jXButton2});

        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jXButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bottomLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExit, btnNext, btnPrevious});

        getContentPane().add(bottom, java.awt.BorderLayout.PAGE_END);

        top.setBackground(new java.awt.Color(255, 255, 255));

        txtRoomID.setText("1");
        txtRoomID.setToolTipText("Please enter your username");
        txtRoomID.setBorder(compoundBorder);
        txtRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomIDActionPerformed(evt);
            }
        });

        txtReligion.setText("Khong");
        txtReligion.setToolTipText("Please enter your username");
        txtReligion.setBorder(compoundBorder);
        txtReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReligionActionPerformed(evt);
            }
        });

        jXLabel8.setText("Tôn giáo");

        jXLabel1.setText("Họ tên");

        txtNation.setText("VietNam");
        txtNation.setToolTipText("Please enter your username");
        txtNation.setBorder(compoundBorder);

        jXLabel7.setText("Quốc tịch");

        txtBirthDay.setDate(new java.util.Date(1447606800000L));
        txtBirthDay.setName(""); // NOI18N

        txtNativeCountry.setText("Kinh");
        txtNativeCountry.setToolTipText("Please enter your username");
        txtNativeCountry.setBorder(compoundBorder);

        jXLabel3.setText("Ngày sinh");

        jXLabel6.setText("Dân tộc");

        jXLabel12.setText("Ngày đến");

        txtUserName.setText("Nguyen Tan Dung");
        txtUserName.setToolTipText("Please enter your username");
        txtUserName.setBorder(compoundBorder);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtIDCard.setText("9999999999999");
        txtIDCard.setToolTipText("Please enter your username");
        txtIDCard.setBorder(compoundBorder);

        txtBirthPlace.setText("Sai Gon");
        txtBirthPlace.setToolTipText("Please enter your username");
        txtBirthPlace.setBorder(compoundBorder);

        jXLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel11.setText("Số CMND");

        jXLabel5.setText("Nơi sinh");

        txtWorkPlace.setText("Ha Noi");
        txtWorkPlace.setToolTipText("Please enter your username");
        txtWorkPlace.setBorder(compoundBorder);

        jXLabel13.setText("Phòng");

        jXLabel10.setText("Nơi làm việc");

        txtOccupation.setText("Thu Tuong");
        txtOccupation.setToolTipText("Please enter your username");
        txtOccupation.setBorder(compoundBorder);

        jXLabel9.setText("Nghề nghiệp");

        jXLabel4.setText("Giới tính");

        btngGender.add(btnMale);
        btnMale.setText(" Nam");
        btnMale.setOpaque(false);
        btnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaleActionPerformed(evt);
            }
        });

        btngGender.add(btnFemale);
        btnFemale.setText(" Nữ");
        btnFemale.setOpaque(false);

        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtArrivalDate.setDate(new java.util.Date(1447606800000L));

        jXLabel15.setText("Email");

        txtEmail.setText("thutuongchinhphu@hotmail.com");
        txtEmail.setToolTipText("Please enter your username");
        txtEmail.setBorder(compoundBorder);

        jXLabel14.setText("Ảnh");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBirthPlace)
                            .addComponent(txtNation)
                            .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMale)
                        .addGap(30, 30, 30)
                        .addComponent(btnFemale)))
                .addGap(32, 32, 32)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                                .addComponent(jXLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGap(2, 2, 2)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWorkPlace)
                            .addComponent(txtEmail)
                            .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jXLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDCard)
                            .addComponent(txtNativeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFemale)
                            .addComponent(btnMale)))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNativeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        topLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jXLabel1, jXLabel10, jXLabel11, jXLabel12, jXLabel13, jXLabel15, jXLabel3, jXLabel4, jXLabel5, jXLabel6, jXLabel7, jXLabel8, jXLabel9, txtArrivalDate, txtBirthDay, txtBirthPlace, txtEmail, txtIDCard, txtNation, txtNativeCountry, txtOccupation, txtReligion, txtRoomID, txtUserName, txtWorkPlace});

        getContentPane().add(top, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomIDActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaleActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Mi coi lại chổ ni phần ShareData hỉ
        // ShareData.getInstance().getCurrentHumanID();
        id = id++;
        String sql = "SELECT * FROM tblHuman WHERE id = ?";
        try (
                Connection cn = Tools.getConn();
                PreparedStatement pst = cn.prepareStatement(sql)
        ;) {
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtUserName.setText(rs.getString(2));
                txtBirthDay.setDate(rs.getDate(3));
                if (rs.getInt(4) == 1) {
                    btnMale.setSelected(true);
                } else {
                    btnFemale.setSelected(true);
                }
                txtBirthPlace.setText(rs.getString(5));
                txtNativeCountry.setText(rs.getString(6));
                txtNation.setText(rs.getString(7));
                txtReligion.setText(rs.getString(8));
                txtOccupation.setText(rs.getString(9));
                txtWorkPlace.setText(rs.getString(10));
                txtIDCard.setText(rs.getString(11));
                txtArrivalDate.setDate(rs.getDate(12));
                InputStream is = rs.getBinaryStream(13);
                System.out.println(is);
                if (is != null) {
                    Image image = ImageIO.read(is);
                    img = image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                    lblImage.setIcon(new ImageIcon(img));
                }
                txtRoomID.setText(rs.getString(14));
                txtEmail.setText(rs.getString(15));
            }

        } catch (SQLException ex) {
            Logger.getLogger(DialogDetailHuman1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogDetailHuman1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    final void initHuman() {
        String sql = "Select * from tblHuman where id = ?";
        try (
                Connection cn = Tools.getConn();
                PreparedStatement pst = cn.prepareStatement(sql);) {
            pst.setInt(1, ShareData.getInstance().getCurrentHumanID());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtUserName.setText(rs.getString(2));
                txtBirthDay.setDate(rs.getDate(3));
                if (rs.getInt(4) == 1) {
                    btnMale.setSelected(true);
                } else {
                    btnFemale.setSelected(true);
                }
                txtBirthPlace.setText(rs.getString(5));
                txtNativeCountry.setText(rs.getString(6));
                txtNation.setText(rs.getString(7));
                txtReligion.setText(rs.getString(8));
                txtOccupation.setText(rs.getString(9));
                txtWorkPlace.setText(rs.getString(10));
                txtIDCard.setText(rs.getString(11));
                txtArrivalDate.setDate(rs.getDate(12));
                InputStream is = rs.getBinaryStream(13);
                System.out.println(is);
                if (is != null) {
                    Image image = ImageIO.read(is);
                    img = image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                    lblImage.setIcon(new ImageIcon(img));
                }
                txtRoomID.setText(rs.getString(14));
                txtEmail.setText(rs.getString(15));
            }

        } catch (SQLException ex) {
            Logger.getLogger(DialogDetailHuman1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogDetailHuman1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private org.jdesktop.swingx.JXButton btnExit;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private org.jdesktop.swingx.JXButton btnNext;
    private org.jdesktop.swingx.JXButton btnPrevious;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXLabel lblImage;
    private javax.swing.JPanel top;
    private org.jdesktop.swingx.JXDatePicker txtArrivalDate;
    private org.jdesktop.swingx.JXDatePicker txtBirthDay;
    private javax.swing.JTextField txtBirthPlace;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDCard;
    private javax.swing.JTextField txtNation;
    private javax.swing.JTextField txtNativeCountry;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtWorkPlace;
    // End of variables declaration//GEN-END:variables
}
